# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='creator',
            name='major_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaraapp.Minor'),
        ),
    ]
