# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0002_auto_20190919_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.TextField(max_length=100)),
            ],
        ),
    ]
