# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0003_counties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='location',
        ),
        migrations.AddField(
            model_name='creator',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imaraapp.Counties'),
        ),
    ]
