# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0004_auto_20190923_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='county',
            field=models.CharField(max_length=100),
        ),
    ]
