# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0005_auto_20190923_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_centre', models.CharField(max_length=100, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imaraapp.Counties')),
            ],
        ),
    ]
