# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0006_urban'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
