# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaraapp', '0007_creator_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='urban_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imaraapp.Urban'),
        ),
    ]
